local objects = {
    {
        id = 1,
        name = "Bone",
        type = "",
        shape = "rectangle",
        x = 2*16,
        y = 2*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 0,
        visible = true,
        properties = {}
    },
    {
        id = 2,
        name = "Torch",
        type = "",
        shape = "rectangle",
        x = 1*16,
        y = 2*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 2,
        visible = true,
        properties = {}
    },
    {
        id = 3,
        name = "Chest",
        type = "",
        shape = "rectangle",
        x = 2*16,
        y = 13*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },
    {
        id = 4,
        name = "Torch",
        type = "",
        shape = "rectangle",
        x = 11*16,
        y = 2*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 2,
        visible = true,
        properties = {}
    },
    {
        id = 5,
        name = "Skeleton",
        type = "",
        shape = "rectangle",
        x = 15*16,
        y = 12*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 2,
        visible = true,
        properties = {}
    },
    {
        id = 6,
        name = "Chest",
        type = "",
        shape = "rectangle",
        x = 27*16,
        y = 2*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },

    {
        id = 7,
        name = "Skull",
        type = "",
        shape = "rectangle",
        x = 28*16,
        y = 9*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },
    {
        id = 8,
        name = "Skull",
        type = "",
        shape = "rectangle",
        x = 8*16,
        y = 19*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },
    {
        id = 9,
        name = "Bone",
        type = "",
        shape = "rectangle",
        x = 18*16,
        y = 10*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },
    {
        id = 10,
        name = "Torch",
        type = "",
        shape = "rectangle",
        x = 11*16,
        y = 9*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },
    {
        id = 11,
        name = "Torch",
        type = "",
        shape = "rectangle",
        x = 23*16,
        y = 6*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },
    {
        id = 12,
        name = "Torch",
        type = "",
        shape = "rectangle",
        x = 28*16,
        y = 15*16,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 3,
        visible = true,
        properties = {}
    },

}

return objects